version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps): "

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps): "
    groups:
      # The AWS SDK dependencies must be updated in unison.
      # See https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1878423518.
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
